import { Platform } from "react-native";

const billScreenStyles = {
	container: {
		flex: 1,
		backgroundColor: "#EFE4D2",
	},
	formContainer: {
		padding: 20,
	},
	scrollContent: {
		paddingBottom: 30,
	},
	formErrorText: {
		color: "#D32F2F",
		fontSize: 15,
		marginTop: 12,
		textAlign: "center",
		fontWeight: "600",
	},
	splitTypeHelperText: {
		color: "#D32F2F",
		fontSize: 12,
		marginTop: 4,
		textAlign: "center",
	},
	errorTextSmall: {
		color: "#D32F2F",
		fontSize: 12,
		marginTop: 2,
		textAlign: "center",
	},
	headerContainer: {
		backgroundColor: "#fff",
		borderRadius: 20,
		padding: 20,
		marginBottom: 30,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.1,
		shadowRadius: 8,
		elevation: 5,
		position: "relative",
		overflow: "hidden",
	},
	headerContent: {
		flexDirection: "row",
		alignItems: "center",
	},
	headerIconContainer: {
		width: 60,
		height: 60,
		borderRadius: 30,
		backgroundColor: "#8B4513",
		justifyContent: "center",
		alignItems: "center",
		marginRight: 16,
	},
	headerIcon: {
		fontSize: 28,
	},
	headerTextContainer: {
		flex: 1,
	},
	headerTitle: {
		fontSize: 28,
		fontWeight: "bold",
		color: "#8B4513",
		marginBottom: 4,
	},
	headerSubtitle: {
		fontSize: 16,
		color: "#666",
		fontStyle: "italic",
	},
	headerAccent: {
		position: "absolute",
		bottom: 0,
		left: 0,
		right: 0,
		height: 4,
		backgroundColor: "#8B4513",
	},
	inputGroup: {
		marginBottom: 20,
	},
	label: {
		fontSize: 16,
		fontWeight: "600",
		color: "#1976D2",
		marginBottom: 8,
	},
	input: {
		borderWidth: 1.5,
		borderColor: "#E0E0E0",
		borderRadius: 12,
		padding: 16,
		backgroundColor: "#fff",
		fontSize: 16,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.1,
		shadowRadius: 3,
		elevation: 2,
	},
	inputError: {
		borderColor: "#F44336",
		borderWidth: 2,
	},
	errorText: {
		color: "#F44336",
		fontSize: 14,
		marginTop: 4,
		marginLeft: 4,
	},
	amountContainer: {
		flexDirection: "row",
		alignItems: "center",
		position: "relative",
	},
	currencySymbol: {
		position: "absolute",
		left: 16,
		fontSize: 16,
		color: "#666",
		zIndex: 1,
		top: Platform.OS === "ios" ? 18 : 16,
	},
	amountInput: {
		paddingLeft: 60,
		flex: 1,
	},
	dateButton: {
		borderWidth: 1.5,
		borderColor: "#E0E0E0",
		borderRadius: 12,
		padding: 16,
		backgroundColor: "#fff",
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.1,
		shadowRadius: 3,
		elevation: 2,
	},
	dateButtonText: {
		fontSize: 16,
		color: "#333",
	},
	noteInput: {
		height: 80,
		textAlignVertical: "top",
	},
	characterCount: {
		fontSize: 12,
		color: "#999",
		textAlign: "right",
		marginTop: 4,
	},
	suggestionsContainer: {
		marginBottom: 12,
	},
	suggestionsLabel: {
		fontSize: 14,
		color: "#666",
		marginBottom: 8,
		fontWeight: "500",
	},
	suggestionChip: {
		backgroundColor: "#E3F2FD",
		borderRadius: 20,
		paddingHorizontal: 12,
		paddingVertical: 6,
		marginRight: 8,
		borderWidth: 1,
		borderColor: "#BBDEFB",
	},
	suggestionChipSelected: {
		backgroundColor: "#1976D2",
		borderColor: "#1976D2",
	},
	suggestionChipText: {
		fontSize: 12,
		color: "#1976D2",
		fontWeight: "500",
	},
	suggestionChipTextSelected: {
		color: "#fff",
	},
	previewContainer: {
		backgroundColor: "#E3F2FD",
		borderRadius: 12,
		padding: 16,
		marginBottom: 20,
		borderLeftWidth: 4,
		borderLeftColor: "#1976D2",
	},
	previewTitle: {
		fontSize: 16,
		fontWeight: "600",
		color: "#1976D2",
		marginBottom: 8,
	},
	previewText: {
		fontSize: 14,
		color: "#1976D2",
		marginBottom: 4,
	},
	previewBreakdown: {
		marginTop: 10,
	},
	previewRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		paddingVertical: 5,
	},
	previewPerson: {
		fontSize: 14,
		color: "#1976D2",
	},
	previewAmount: {
		fontSize: 14,
		color: "#1976D2",
		fontWeight: "600",
	},
	dropdown: {
		borderColor: "#E0E0E0",
		borderWidth: 1.5,
		borderRadius: 12,
		backgroundColor: "#fff",
		minHeight: 50,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.1,
		shadowRadius: 3,
	},
	dropdownContainer: {
		borderColor: "#E0E0E0",
		borderRadius: 12,
		backgroundColor: "#fff",
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.15,
		shadowRadius: 6,
	},
	dropdownText: {
		fontSize: 16,
		color: "#333",
	},
	dropdownPlaceholder: {
		color: "#999",
		fontSize: 16,
	},
	badgeDot: {
		backgroundColor: "#1976D2",
	},
	badgeText: {
		color: "#fff",
		fontSize: 12,
	},
	splitDropdownContainer: {
		maxHeight: 300,
	},
	searchContainer: {
		borderBottomWidth: 1,
		borderBottomColor: "#eee",
		paddingHorizontal: 10,
		paddingVertical: 8,
	},
	searchInput: {
		borderWidth: 1,
		borderColor: "#ddd",
		borderRadius: 8,
		paddingHorizontal: 12,
		paddingVertical: 8,
		fontSize: 14,
		backgroundColor: "#f8f9fa",
	},
	itemSeparator: {
		height: 1,
		backgroundColor: "#f0f0f0",
		marginHorizontal: 10,
	},
	splitTypeContainer: {
		flexDirection: "row",
		gap: 10,
	},
	splitTypeRow: {
		flexDirection: "row",
		justifyContent: "space-evenly",
		alignItems: "center",
		marginTop: 8,
		marginBottom: 2,
	},
	splitTypeButton: {
		paddingVertical: 8,
		paddingHorizontal: 25,
		borderRadius: 20,
		borderWidth: 1,
		borderColor: "#1976D2",
		backgroundColor: "#fff",
	},
	splitTypeActive: {
		backgroundColor: "#1976D2",
	},
	splitTypeDisabled: {
		opacity: 0.4,
	},
	splitTypeText: {
		color: "#1976D2",
		fontWeight: "600",
		fontSize: 15,
	},
	splitTypeTextActive: {
		color: "#fff",
	},
	splitTypeTextDisabled: {
		color: "#888",
	},
	customSplitContainer: {
		backgroundColor: "#F5F5F5",
		borderRadius: 12,
		padding: 15,
		marginBottom: 20,
	},
	customSplitRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		marginBottom: 10,
	},
	customSplitName: {
		flex: 1,
		fontSize: 14,
		color: "#333",
		fontWeight: "500",
	},
	customSplitInputContainer: {
		flexDirection: "row",
		alignItems: "center",
		flex: 1,
		justifyContent: "flex-end",
	},
	customSplitPrefix: {
		marginRight: 5,
		fontSize: 14,
		color: "#666",
	},
	customSplitInput: {
		borderWidth: 1,
		borderColor: "#E0E0E0",
		borderRadius: 8,
		paddingHorizontal: 10,
		paddingVertical: 8,
		backgroundColor: "#fff",
		width: 80,
		textAlign: "center",
	},
	imagePickerButton: {
		backgroundColor: "#673AB7",
		borderRadius: 12,
		paddingVertical: 16,
		alignItems: "center",
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.1,
		shadowRadius: 3,
		elevation: 2,
	},
	imagePickerButtonText: {
		color: "#fff",
		fontSize: 16,
		fontWeight: "600",
	},
	imagePreviewContainer: {
		alignItems: "center",
		marginBottom: 10,
	},
	imagePreview: {
		width: "100%",
		height: 200,
		borderRadius: 12,
		resizeMode: "cover",
		marginBottom: 10,
		borderWidth: 1,
		borderColor: "#E0E0E0",
	},
	clearImageButton: {
		backgroundColor: "#F44336",
		borderRadius: 8,
		paddingVertical: 10,
		paddingHorizontal: 15,
		flexDirection: "row",
		alignItems: "center",
		gap: 5,
	},
	clearImageButtonText: {
		color: "#fff",
		fontSize: 14,
		fontWeight: "bold",
	},
	addButton: {
		backgroundColor: "#4CAF50",
		borderRadius: 12,
		paddingVertical: 18,
		alignItems: "center",
		marginTop: 5,
		shadowColor: "#4CAF50",
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.3,
		shadowRadius: 8,
		elevation: 6,
	},
	addButtonDisabled: {
		backgroundColor: "#CCCCCC",
		shadowOpacity: 0.1,
	},
	addButtonText: {
		color: "#fff",
		fontWeight: "bold",
		fontSize: 18,
		letterSpacing: 0.5,
	},
};

export default billScreenStyles;
